import * as fs from 'node:fs'
import * as path from 'node:path'

import type { IconDefinition } from '../types'
import { fail } from '../utils/args'
import { ensureDir, findWorkspaceRoot } from '../utils/fs'
import {
  generateIconModule,
  generateIndexFile,
  generateLucideVersionModule,
  isValidIdentifier,
  kebabToPascal,
  readLucideSource,
  type IconAlias,
} from '../utils/icons'

export async function generateIcons(packageDir: string) {
  const workspaceRoot = findWorkspaceRoot(packageDir)
  const cacheDir = path.join(workspaceRoot, '.lucide-cache')
  const iconsSourceDir = path.join(cacheDir, 'icons')
  const outputDir = path.join(packageDir, 'src', 'icons')
  const indexFile = path.join(packageDir, 'src', 'index.ts')
  const versionFile = path.join(packageDir, 'src', 'lucide-version.ts')

  if (!fs.existsSync(iconsSourceDir)) {
    fail('Icons source directory not found. Run fetch-icons first.')
  }

  fs.rmSync(outputDir, { recursive: true, force: true })
  ensureDir(outputDir)

  const svgFiles = fs.readdirSync(iconsSourceDir).filter(file => file.endsWith('.svg'))
  const icons: IconDefinition[] = []
  const seenComponents = new Set<string>()

  for (const file of svgFiles) {
    const name = file.replace('.svg', '')
    const componentName = kebabToPascal(name)

    // A name that maps to an invalid identifier (e.g. starts with a digit) would
    // emit `export const 0Foo = ...` — broken JS. Skip loudly instead.
    if (!isValidIdentifier(componentName)) {
      console.warn(`Skipping icon "${name}": "${componentName}" is not a valid identifier`)
      continue
    }

    // Two basenames can normalize to the same Pascal identifier; emitting both
    // would produce a duplicate `export const`. Keep the first, warn on the rest.
    if (seenComponents.has(componentName)) {
      console.warn(`Skipping icon "${name}": duplicate component "${componentName}"`)
      continue
    }
    seenComponents.add(componentName)

    const svgPath = path.join(iconsSourceDir, file)
    const svgContent = fs.readFileSync(svgPath, 'utf8')

    icons.push({ name, componentName, svgContent })
    fs.writeFileSync(
      path.join(outputDir, `${name}.ts`),
      generateIconModule({ name, componentName, svgContent }),
    )
  }

  const aliases = collectAliases(iconsSourceDir, icons)
  const source = readLucideSource(cacheDir)

  fs.writeFileSync(versionFile, generateLucideVersionModule(source))
  fs.writeFileSync(indexFile, generateIndexFile(icons, aliases, source))

  const iconListContent = `// Auto-generated by @lucide-react-taro/generate — DO NOT EDIT\nexport const iconList = ${JSON.stringify(
    icons.map(icon => ({
      name: icon.name,
      componentName: icon.componentName,
    })),
    null,
    2,
  )} as const;\n`

  for (const cliPackageName of ['taro-lucide-find', 'taro-lucide-show']) {
    const targetDir = path.join(workspaceRoot, 'packages', cliPackageName, 'src')
    ensureDir(targetDir)
    fs.writeFileSync(path.join(targetDir, 'icon-list.ts'), iconListContent)
  }

  console.log(
    `Generated ${icons.length} icon modules (+${aliases.length} aliases)` +
      (source ? ` from lucide ${source.ref}` : ''),
  )
}

/**
 * Collect alias exports from lucide's per-icon metadata (`icons/<name>.json` `aliases`),
 * so renamed/deprecated names keep resolving to their canonical component. Skips any alias
 * that collides with a canonical icon, a reserved export, or an already-seen alias.
 */
function collectAliases(iconsSourceDir: string, icons: IconDefinition[]): IconAlias[] {
  const canonicalComponents = new Set(icons.map(icon => icon.componentName))
  const reserved = new Set([
    'createIcon',
    'LucideTaroProvider',
    'LUCIDE_VERSION',
    'LUCIDE_COMMIT',
  ])
  const seen = new Set<string>()
  const aliases: IconAlias[] = []

  for (const icon of icons) {
    const metaPath = path.join(iconsSourceDir, `${icon.name}.json`)
    if (!fs.existsSync(metaPath)) continue

    let meta: { aliases?: Array<string | { name?: string }> }
    try {
      meta = JSON.parse(fs.readFileSync(metaPath, 'utf8'))
    } catch {
      continue
    }

    if (!Array.isArray(meta.aliases)) continue

    for (const entry of meta.aliases) {
      const aliasName = typeof entry === 'string' ? entry : entry?.name
      if (!aliasName || typeof aliasName !== 'string') continue

      const aliasComponent = kebabToPascal(aliasName)
      if (
        !isValidIdentifier(aliasComponent) ||
        canonicalComponents.has(aliasComponent) ||
        reserved.has(aliasComponent) ||
        seen.has(aliasComponent)
      ) {
        continue
      }

      seen.add(aliasComponent)
      aliases.push({ aliasName, aliasComponent, canonicalComponent: icon.componentName })
    }
  }

  return aliases
}
