import * as fs from 'node:fs'
import * as path from 'node:path'

import type { IconDefinition } from '../types'

export const LUCIDE_REPO = 'https://github.com/lucide-icons/lucide.git'

/** The lucide ref the icon set was generated from (recorded for reproducible, auditable builds). */
export interface LucideSource {
  ref: string
  commit: string
}

/** A deprecated/alternative lucide name re-exported to its canonical component. */
export interface IconAlias {
  aliasName: string
  aliasComponent: string
  canonicalComponent: string
}

const LUCIDE_SOURCE_FILE = 'lucide-source.json'

export function kebabToPascal(value: string) {
  return value
    .split('-')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

/** A name safe to emit as a JS/TS `export const <name>` (e.g. not starting with a digit). */
export function isValidIdentifier(name: string) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)
}

export function escapeSvgForJs(svgContent: string) {
  return svgContent
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '')
    .replace(/\r/g, '')
    .replace(/\s+/g, ' ')
    .trim()
}

/** Record which lucide ref/commit the cache was fetched at, so generate-icons can stamp it. */
export function writeLucideSource(cacheDir: string, source: LucideSource) {
  fs.writeFileSync(
    path.join(cacheDir, LUCIDE_SOURCE_FILE),
    `${JSON.stringify(source, null, 2)}\n`,
  )
}

export function readLucideSource(cacheDir: string): LucideSource | null {
  try {
    return JSON.parse(
      fs.readFileSync(path.join(cacheDir, LUCIDE_SOURCE_FILE), 'utf8'),
    ) as LucideSource
  } catch {
    return null
  }
}

export function generateIconModule(icon: IconDefinition) {
  const escaped = escapeSvgForJs(icon.svgContent)

  return `// Auto-generated by @lucide-react-taro/generate — DO NOT EDIT
import { createIcon } from '../create-icon';

export const ${icon.componentName} = /*#__PURE__*/ createIcon("${escaped}", "${icon.componentName}");
`
}

export function generateLucideVersionModule(source: LucideSource | null) {
  const version = source?.ref ?? 'unknown'
  const commit = source?.commit ?? 'unknown'

  return `// Auto-generated by @lucide-react-taro/generate — DO NOT EDIT
export const LUCIDE_VERSION = ${JSON.stringify(version)};
export const LUCIDE_COMMIT = ${JSON.stringify(commit)};
`
}

export function generateIndexFile(
  icons: IconDefinition[],
  aliases: IconAlias[] = [],
  source: LucideSource | null = null,
) {
  const iconExports = icons
    .map(icon => {
      const escaped = escapeSvgForJs(icon.svgContent)
      return `export const ${icon.componentName} = /*#__PURE__*/ createIcon("${escaped}", "${icon.componentName}");`
    })
    .join('\n')

  const aliasExports = aliases
    .map(
      alias =>
        `export const ${alias.aliasComponent} = ${alias.canonicalComponent};`,
    )
    .join('\n')

  // Every icon and alias is ALSO exported with an `Icon` suffix, matching lucide-react
  // (`House` is also exported as `HouseIcon`, so `HouseIcon === House`). This avoids
  // import-name collisions with other libraries or your own code. Emitted as a trailing
  // block so every name it references is already declared above; a suffixed name that
  // would shadow an existing export is skipped.
  const emitted = new Set<string>([
    'createIcon',
    'LucideTaroProvider',
    'LUCIDE_VERSION',
    'LUCIDE_COMMIT',
    ...icons.map(icon => icon.componentName),
    ...aliases.map(alias => alias.aliasComponent),
  ])
  const suffixLines: string[] = []
  const addSuffixed = (name: string, target: string) => {
    const suffixed = `${name}Icon`
    if (emitted.has(suffixed)) return
    emitted.add(suffixed)
    suffixLines.push(`export const ${suffixed} = ${target};`)
  }
  for (const icon of icons) addSuffixed(icon.componentName, icon.componentName)
  for (const alias of aliases) addSuffixed(alias.aliasComponent, alias.canonicalComponent)
  const suffixExports = suffixLines.join('\n')

  const sourceComment = source
    ? `// Icons generated from lucide ${source.ref} (commit ${source.commit})\n`
    : ''

  return `// Auto-generated by @lucide-react-taro/generate — DO NOT EDIT
${sourceComment}import { createIcon } from './create-icon';
export { createIcon };
export { LucideTaroProvider } from './context';
export type { IconProps, LucideTaroConfig } from './types';
export type { LucideTaroProviderProps } from './context';
export { LUCIDE_VERSION, LUCIDE_COMMIT } from './lucide-version';

${iconExports}
${aliasExports ? `\n// --- Aliases: deprecated / alternative lucide names ---\n${aliasExports}\n` : ''}${suffixExports ? `\n// --- Icon-suffixed names (lucide-react parity: \`Foo\` is also exported as \`FooIcon\`) ---\n${suffixExports}\n` : ''}`
}
